In [1]:
import numpy as np


In [2]:
#1.Crie um array NumPy unidimensional com os números de 1 a 10.
OneDim = np.arange (1, 11)

print (OneDim)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
#2. Crie um array NumPy bidimensional 3x3 preenchido com zeros.
arrayzeros = np.zeros((3,3))
#arrayzeros.ndim
#arrayzeros.shape
print(arrayzeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
#3. Crie um array NumPy bidimensional 4x4 preenchido com uns.
ArrayOne= np.ones((4,4) , dtype=int)
ArrayOne.shape
print (ArrayOne)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [5]:
#4. Crie um array NumPy com 20 valores aleatórios entre 0 e 100.
Randomix = np.random.randint(0, 100, 20, int)
print(Randomix)

[39 63 29 61 38 25 66 88 43  9 45 33 57 72 74 84  4 31 54 55]


In [6]:
#5 Crie um array NumPy unidimensional com espaçamento de 0.5 entre 0 e 10.
answ5 = np.arange(1, 10.5, 0.5)
print(answ5)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


In [7]:
#6 Crie um array NumPy bidimensional 5x5 com valores aleatórios inteiros entre 1 e 100.
answ6 = np.random.randint(0, 100,(5,5), int)

print(answ6)



[[ 1 93 65 74 85]
 [38 78 45 60 20]
 [94 96 61 33  1]
 [ 0 35 71 95 77]
 [86 75 49 87 16]]


In [8]:
#7 Dada a matriz A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
#crie um array NumPy contendo apenas a segunda coluna da matriz A.

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

SecondColumn = (A[: , 1])

print(SecondColumn)

[2 5 8]


In [9]:
#8 Dado o array NumPy x = [1, 2, 3, 4, 5],
#crie um novo array onde todos os valores pares sejam substituídos por -1.

x = np.array ([1, 2, 3, 4, 5])

new_array = np.where(x % 2 ==0, -1, x)

print (new_array)



[ 1 -1  3 -1  5]


In [10]:
#9 Dado o array NumPy x = [1, 2, 3, 4, 5],
#crie um novo array onde todos os valores maiores que 2 sejam substituídos por 0.

y = np.array([1, 2, 3, 4, 5])

New_y = np.where (y > 2, 0 ,y)

print(New_y)



[1 2 0 0 0]


In [11]:
#10 Dado o array NumPy x = [1, 2, 3, 4, 5],
#normalize os valores do array de forma que a soma seja igual a 1.

z = np.array([1,2,3,4,5])

z_normalized = z / np.sum(z)

print(z_normalized)


[0.06666667 0.13333333 0.2        0.26666667 0.33333333]


In [12]:
#11 Dada a matriz A = [[1, 2], [3, 4]] e a matriz B = [[5, 6], [7, 8]],
#calcule a multiplicação matricial entre A e B.


A = np.array([[1, 2], [3, 4]])

B = np.array([[5, 6], [7, 8]])

Produto = np.dot (A, B)

print(Produto)

[[19 22]
 [43 50]]


In [13]:
#12 Dado o array NumPy x = [1, 2, 3],
#crie um novo array com os valores de x repetidos três vezes.

npyx = np.array([1, 2, 3])

newOne = np.tile(npyx, 3)

print(newOne)



3

[1 2 3 1 2 3 1 2 3]


3

In [14]:
#13 Dado o array NumPy x = [1, 2, 3],
#crie um novo array com os valores de x repetidos lado a lado três vezes.

npxyz = np.array([1,2,3])

newiestOne = np.repeat(npxyz, 3)

print(newiestOne)



[1 1 1 2 2 2 3 3 3]


In [15]:
# 14 Dado o array NumPy x = [1, 2, 3], crie um novo array com os valores de x repetidos verticalmente três vezes.

nparray = np.array([1,2,3])

new_nparray = np.tile(nparray,(3, 1))

print(new_nparray)



[[1 2 3]
 [1 2 3]
 [1 2 3]]
